rem 请根据VC的安装目录修改VCDir！
@echo off
set Masm32Dir=
set VCDir=F:\programs\vs2015\VC\bin
set path=%PATH%;%Masm32Dir%\Bin;%Masm32Dir%;%VCDir%
set Masm32Dir=C:\Users\jojo\Desktop\5\Masm32
set include=%Masm32Dir%\Include;%include%
set lib=%Masm32Dir%\lib;%lib%
set Masm32Dir=
chcp 437
echo on